// Generated by CoffeeScript 1.7.1
(function() {
  var Ratestate, debug, fs, hash, util,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  util = require("util");

  fs = require("fs");

  hash = require("object-hash");

  debug = require("debug")("Ratestate:Ratestate");

  Ratestate = (function() {
    function Ratestate(config) {
      var key, val;
      this._desiredStates = {};
      this._currentHashes = {};
      this._desiredHashes = {};
      this._entityIds = [];
      this._workerInProgress = [];
      this._pointer = 0;
      this._config = {
        interval: 30,
        hashFunc: hash,
        worker: function(entityId, state, cb) {
          console.log("Processing " + entityId);
          return cb(null);
        }
      };
      if (config != null) {
        for (key in config) {
          val = config[key];
          this._config[key] = val;
        }
      }
    }

    Ratestate.prototype.setState = function(entityId, desiredState) {
      var desiredHash;
      desiredHash = this._config.hashFunc(desiredState);
      if ((this._currentHashes[entityId] != null) && this._currentHashes[entityId] === desiredHash) {
        return;
      }
      if (__indexOf.call(this._entityIds, entityId) < 0) {
        this._entityIds.push(entityId);
      }
      this._desiredHashes[entityId] = desiredHash;
      return this._desiredStates[entityId] = desiredState;
    };

    Ratestate.prototype.run = function() {
      var desiredState, entityId, i, len, _i, _results;
      len = this._entityIds.length - 1;
      _results = [];
      for (i = _i = 0; 0 <= len ? _i <= len : _i >= len; i = 0 <= len ? ++_i : --_i) {
        if (!(i >= this._pointer)) {
          continue;
        }
        entityId = this._entityIds[i];
        desiredState = this._desiredStates[entityId];
        this._pointer++;
        if (this._pointer > len) {
          this._pointer = 0;
        }
        if (this._currentHashes[entityId] !== this._desiredHashes[entityId]) {
          if (this._workerInProgress[entityId] === true) {
            continue;
          }
          this._workerInProgress[entityId] = true;
          this._config.worker(entityId, desiredState, (function(_this) {
            return function(err) {
              _this._workerInProgress[entityId] = false;
              if (!err) {
                _this._currentHashes[entityId] = _this._desiredHashes[entityId];
                return delete _this._desiredStates[entityId];
              }
            };
          })(this));
          break;
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Ratestate.prototype.start = function() {
      return this.timer = setInterval(this.run.bind(this), this._config.interval);
    };

    Ratestate.prototype.stop = function() {
      return clearInterval(this.timer);
    };

    return Ratestate;

  })();

  module.exports = Ratestate;

}).call(this);

//# sourceMappingURL=Ratestate.map
